spring:
  datasource:
    #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minioa
    username: root
    password: clz11053

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

server:
  address: 2409:8a34:2060:faf0:5554:e843:39ee:3430
  port: 5531
